config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html
  get 'topics/top' => 'topics#top'
  resources :topics
  resources :topic2s
  resources :topic3s
  resources :topic4s
  resources :topic5s
  root "topics#top"

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/topic.rb
class Topic < ApplicationRecord
end

app/models/topic2.rb
class Topic2 < ApplicationRecord
end

app/models/topic3.rb
class Topic3 < ApplicationRecord
end

app/models/topic4.rb
class Topic4 < ApplicationRecord
end

app/models/topic5.rb
class Topic5 < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/topic2s_controller.rb
class Topic2sController < ApplicationController
    def new
        @topic2 = Topic2.new
    end
    def show
        @topic2 = Topic2.find_by(id: params[:id])
        @topic3 = Topic3.new
    end
    def create
        @topic2 = Topic2.new(topic2_params)
        #params[:topic2][:question] ? @topic2.question = params[:topic2][:question].join("") : false
        if @topic2.save
            flash[:notice] = "診断が完了しました"
            redirect_to topic2_path(@topic2.id)
        else
            redirect_to :action => "new"
        end
    end
    private
      def topic2_params
          params.require(:topic2).permit(:id, :question)
      end
end

app/controllers/topic3s_controller.rb
class Topic3sController < ApplicationController
    def new
        @topic3 = Topic3.new
      end
      def show
        @topic3 = Topic3.find_by(id: params[:id])
        @topic4 = Topic4.new
      end
      def create
        @topic3 = Topic3.new(topic3_params)
        #params[:topic3][:question] ? @topic3.question = params[:topic3][:question].join("") : false
        if @topic3.save
            flash[:notice] = "診断が完了しました"
            redirect_to topic3_path(@topic3.id)
        else
            redirect_to :action => "new"
        end
      end
    private
      def topic3_params
          params.require(:topic3).permit(:id, :question) 
      end
end

app/controllers/topic4s_controller.rb
class Topic4sController < ApplicationController
    def new
        @topic4 = Topic4.new
    end
  
    def show
        @topic4 = Topic4.find_by(id: params[:id])
        @topic5 = Topic5.new
    end
  
    def create
        @topic4 = Topic4.new(topic4_params)
        #params[:topic4][:question] ? @topic4.question = params[:topic4][:question].join("") : false
        if @topic4.save
            flash[:notice] = "診断が完了しました"
            redirect_to topic4_path(@topic4.id)
        else
            redirect_to :action => "new"
        end
    end
    
    private
    def topic4_params
        params.require(:topic4).permit(:id, :question)
    end
end

app/controllers/topic5s_controller.rb
class Topic5sController < ApplicationController
    def new
        @topic5 = Topic5.new
    end
  
    def show
        @topic5 = Topic5.find_by(id: params[:id])
    end
  
    def create
        @topic5 = Topic5.new(topic5_params)
        if @topic5.save
            flash[:notice] = "診断が完了しました"
            redirect_to topic5_path(@topic5.id)
        else
            redirect_to :action => "new"
        end
    end
    
    private
    def topic5_params
        params.require(:topic5).permit(:id, :question)
    end
end

app/controllers/topics_controller.rb
class TopicsController < ApplicationController
    def top
    end
    def new
      @topic = Topic.new
    end
  
    def show
      @topic = Topic.find_by(id: params[:id])
      @topic2 = Topic2.new
    end
  
    def create
      @topic = Topic.new(topic_params)
    #params[:topic][:question] ? @topic.question = params[:topic][:question].join("") : false
      if @topic.save
          flash[:notice] = "診断が完了しました"
          redirect_to topic_path(@topic.id)
      else
          redirect_to :action => "new"
      end
    end
  
  private
    def topic_params
        params.require(:topic).permit(:id, :question)
    end
  
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/topic2s_helper.rb
module Topic2sHelper
end

app/helpers/topic3s_helper.rb
module Topic3sHelper
end

app/helpers/topic4s_helper.rb
module Topic4sHelper
end

app/helpers/topic5s_helper.rb
module Topic5sHelper
end

app/helpers/topics_helper.rb
module TopicsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>念能力診断</title>
    <link rel="icon" href="/assets/logo.ico">
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
    <!--==============レイアウトを制御する独自のCSSを読み込み===============-->
    <link href="https://coco-factory.jp/ugokuweb/wp-content/themes/ugokuweb/data/reset.css" rel="stylesheet">
    <link href="https://coco-factory.jp/ugokuweb/wp-content/themes/ugokuweb/data/4-1-4/css/4-1-4.css" rel="stylesheet">
  </head>

  <body>
    <%= yield %>
    <!--==============JQuery読み込み===============-->
    <script src="https://cdnjs.cloudflare.com/ajax/libs/particlesjs/2.2.2/particles.min.js"></script>
    <script src="https://code.jquery.com/jquery-3.4.1.min.js"
    integrity="sha256-CSXorXvZcTkaix6Yvo6HppcZGetbYMGWSFlBw8HfCJo=" crossorigin="anonymous"></script>
    <script src="https://coco-factory.jp/ugokuweb/wp-content/themes/ugokuweb/data/4-1-4/js/4-1-4.js"></script>
  </body>
</html>

app/views/topic2s/show.html.erb
<div class="container-2">
    <div class="sindan-container">
        <% if @topic2.question == 3  %>
            <div class="col-12">
                <p>Q3.ハンターたる者、時に嘘もつかなくてはいけません。あなたはどう行動しますか？</p>
            </div>
            <%= form_for(@topic3) do |f| %>
                <div class="col-6">
                    <div class="col-7">
                        <%= f.radio_button :question, "6", id: "question_6" %>
                        <label for="question_6">バレなければ嘘は使う</label>
                    </div>
                    <div class="col-7">
                        <%= f.radio_button :question, "7", id: "question_7" %>
                        <label for="question_7">極力嘘はつきたくない</label>
                    </div>
                </div>
                <div class="sindanbotan">
                    <%= f.submit "次へ", class: "button" %>
                </div>
            <% end %>
        <% end %>

        <% if @topic2.question == 4  %>
            <div class="col-12">
                <p>Q3.自分が悩みを抱えてしまったら、どうやって解決しますか？</p>
            </div>
            <%= form_for(@topic3) do |f| %>
                <div class="col-6">
                    <div class="col-7">
                        <%= f.radio_button :question, "7", id: "question_7" %>
                        <label for="question_7">即行動に移す</label>
                    </div>
                    <div class="col-7">
                        <%= f.radio_button :question, "8", id: "question_8" %>
                        <label for ="question_8">結論が出るまで考え抜く</label>
                    </div>
                </div>
                <div class="sindanbotan">
                    <%= f.submit "次へ", class: "button" %>
                </div>
            <% end %>
        <% end %>

        <% if @topic2.question == 5  %>
            <div class="col-12">
                <p>Q3.仲間のハンターが悩みを抱えているようだ。あなたはどう行動しますか？</p>
            </div>
            <%= form_for(@topic3) do |f| %>
                <div class="col-6">
                    <div class="col-7">
                        <%= f.radio_button :question, "8", id: "question_8" %>
                        <label for="question_8">相談に乗る</label>
                    </div>
                    <div class="col-7">
                        <%= f.radio_button :question, "9", id: "question_9" %>
                        <label for="question_9">そっとしておく</label>
                    </div>
                </div>
                <div class="sindanbotan">
                    <%= f.submit "次へ", class: "button" %>
                </div>
            <% end %>
        <% end %>
    </div>
</div>

app/views/topic3s/show.html.erb
<div class="container-2">
    <div class="sindan-container">
        <% if @topic3.question == 6  %>
            <div class="col-12">
                <p>Q4.あなたが興味をもった対象はずっと同じですか？それとも次々に変わっていきますか？</p>
            </div>
            <%= form_for(@topic4) do |f| %>
                <div class="col-6">
                    <div class="col-7">
                        <%= f.radio_button :question, "12", id: "question_12" %>
                        <label for="question_12">ずっと同じだ</label>
                    </div>
                    <div class="col-7">
                        <%= f.radio_button :question, "10", id: "question_10" %>
                        <label for="question_10">次々変わる</label>
                    </div>
                </div>
                <div class="sindanbotan">
                    <%= f.submit "次へ", class: "button" %>
                </div>
            <% end %>
        <% end %>

        <% if @topic3.question == 7  %>
            <div class="col-12">
                <p>Q4.あなたが感極まった時、あるいは悔しさが溢れてしまった時、人前でも涙を見せますか？</p>
            </div>
            <%= form_for(@topic4) do |f| %>
                <div class="col-6">
                    <div class="col-7">
                        <%= f.radio_button :question, "13", id: "question_13" %>
                        <label for="question_13">涙を見せることもある</label>
                    </div>
                    <div class="col-7">
                        <%= f.radio_button :question, "12", id: "question_12" %>
                        <label for="question_12">人前で涙は見せない</label>
                    </div>
                </div>
                <div class="sindanbotan">
                    <%= f.submit "次へ", class: "button" %>
                </div>
            <% end %>
        <% end %>

        <% if @topic3.question == 8  %>
            <div class="col-12">
                <p>Q4.戦うために武器は必要だと思いますか？</p>
            </div>
            <%= form_for(@topic4) do |f| %>
                <div class="col-6">
                    <div class="col-7">
                        <%= f.radio_button :question, "12", id: "question_12" %>
                        <label for="question_12">絶対に必要だ</label>
                    </div>
                    <div class="col-7">
                        <%= f.radio_button :question, "13", id: "question_13" %>
                        <label for="question_13">必ずしも必要ではない</label>
                    </div>
                </div>
                <div class="sindanbotan">
                    <%= f.submit "次へ", class: "button" %>
                </div>
            <% end %>
        <% end %>

        <% if @topic3.question == 9  %>
            <div class="col-12">
                <p>Q4.自分のペースと周囲のペース。あなたはどちらを重要視しますか？</p>
            </div>
            <%= form_for(@topic4) do |f| %>
                <div class="col-6">
                    <div class="col-7">
                        <%= f.radio_button :question, "11", id: "question_11" %>
                        <label for="question_11">自分</label>
                    </div>
                    <div class="col-7">
                        <%= f.radio_button :question, "10", id: "question_10" %>
                        <label for="question_10">周囲</label>
                    </div>
                </div>
                <div class="sindanbotan">
                    <%= f.submit "次へ", class: "button" %>
                </div>
            <% end %>
        <% end %>
    </div>
</div>

app/views/topic4s/show.html.erb
<div class="container-2">
    <div class="sindan-container">
        <% if @topic4.question == 10  %>
            <div class="col-12">
                <p>Q5.あなたは、一人で静かに盛り上がるのと、大勢でにぎやかに盛り上がるのと、どちらを好みますか？</p>
            </div>
            <%= form_for(@topic5) do |f| %>
                <div class="col-6">
                    <div class="col-7">
                        <%= f.radio_button :question, "15", id: "question_15" %>
                        <label for="question_15">一人で静かに</label>
                    </div>
                    <div class="col-7">
                        <%= f.radio_button :question, "18", id: "question_18" %>
                        <label for="question_18">大勢でにぎやかに</label>
                    </div>
                </div>
                <div class="sindanbotan">
                    <%= f.submit "次へ", class: "button" %>
                </div>
            <% end %>
        <% end %>

        <% if @topic4.question == 11  %>
            <div class="col-12">
                <p>Q5.ハンターの世界でもファッションセンスは大事です。あなたはどういう服装を選びますか？</p>
            </div>
            <%= form_for(@topic5) do |f| %>
                <div class="col-6">
                    <div class="col-7">
                        <%= f.radio_button :question, "20", id: "question_20" %>
                        <label for="question_20">売れ筋の服を好む</label>
                    </div>
                    <div class="col-7">
                        <%= f.radio_button :question, "19", id: "question_19" %>
                        <label for="question_19">誰も着ないような服を選ぶ</label>
                    </div>
                </div>
                <div class="sindanbotan">
                    <%= f.submit "次へ", class: "button" %>
                </div>
            <% end %>
        <% end %>

        <% if @topic4.question == 12  %>
            <div class="col-12">
                <p>Q5.あらゆる状況を考えておかなければならないハンター。あなたの想像力はどのぐらいですか？</p>
            </div>
            <%= form_for(@topic5) do |f| %>
                <div class="col-6">
                    <div class="col-7">
                        <%= f.radio_button :question, "20", id: "question_20" %>
                        <label for="question_20">一般的な想像力だ</label>
                    </div>
                    <div class="col-7">
                        <%= f.radio_button :question, "16", id: "question_16" %>
                        <label for="question_16">想像力が豊かすぎて、考えすぎな面もある</label>
                    </div>
                </div>
                <div class="sindanbotan">
                    <%= f.submit "次へ", class: "button" %>
                </div>
            <% end %>
        <% end %>

        <% if @topic4.question == 13  %>
            <div class="col-12">
                <p>Q5.ところで、昨日食べた物のことを覚えていますか？</p>
            </div>
            <%= form_for(@topic5) do |f| %>
                <div class="col-6">
                    <div class="col-7">
                        <%= f.radio_button :question, "14", id: "question_14" %>
                        <label for="question_14">しっかりすべて覚えている</label>
                    </div>
                    <div class="col-7">
                        <%= f.radio_button :question, "17", id: "question_17" %>
                        <label for="question_17">あまり覚えていない</label>
                    </div>
                </div>
                <div class="sindanbotan">
                    <%= f.submit "次へ", class: "button" %>
                </div>
            <% end %>
        <% end %>
    </div>
</div>

app/views/topic5s/show.html.erb
<div class="container-3">
    <% if @topic5.question == 14  %>
        <div class="col-13">
            <p>強化系</p>
        </div>
        <div class="col-10">
            <%= image_tag '/assets/gon.jpg', size: "250x250", class: 'hoge' %>
        </div>
        <div class="col-8">
            <p>強固な意思を持ち、時にワガママな性格のアナタは強化系です！<br>
            バトルや力仕事で大活躍できる、パワーファイターに向いています。</p>
        </div>
    <% end %>

    <% if @topic5.question == 15  %>
        <div class="col-13">
            <p>変化形</p>
        </div>
        <div class="col-10">
            <%= image_tag '/assets/kirua.jpg', size: "250x250", class: 'hoge' %>
        </div>
        <div class="col-8">
            <p>ミステリアスな人だと思われがちなアナタは変化形！<br>
            オーラを身体から離さずに、素早い動きや細かな作業を得意とするハンターです。</p>
        </div>
    <% end %>

    <% if @topic5.question == 16  %>
        <div class="col-13">
            <p>具現化系</p>
        </div>
        <div class="col-10">
            <%= image_tag '/assets/kurapika.jpg', size: "250x250", class: 'hoge' %>
        </div>
        <div class="col-8">
            <p>細かいことにも目の届くアナタは具現化系！<br>
            持ち前の冷静な判断力や集中力で、何かを教えたり指導したりするのが得意でしょう。</p>
        </div>
    <% end %>

    <div class="col-15">
        <% if @topic5.question == 17  %>
            <div class="col-13">
                <p>放出系</p>
            </div>
            <div class="col-10">
                <%= image_tag '/assets/reorio.jpg', size: "250x250", class: 'hoge' %>
            </div>
            <div class="col-8">
                <p>上に厚いアナタは放出系にピッタリ！<br>
                面倒見がよいため仲間や後輩から慕われやすく、客商売に向いたハンターかもしれません。</p>
            </div>
        <% end %>
    </div>

    <% if @topic5.question == 18  %>
        <div class="col-13">
            <p>操作系</p>
        </div>
        <div class="col-10">
            <%= image_tag '/assets/irumi.jpg', size: "250x250", class: 'hoge' %>
        </div>
        <div class="col-8">
            <p>細かいとに機転が効き、筋道を考えられるアナタは操作系です！<br>
            理論派のハンターとして、きっと活躍できるでしょう。</p>
        </div>
    <% end %>

    <% if @topic5.question == 19  %>
        <div class="col-13">
            <p>特質系</p>
        </div>
        <div class="col-10">
            <%= image_tag '/assets/kuroro.jpg', size: "250x250", class: 'hoge' %>
        </div>
        <div class="col-8">
            <p>他の人と一線を画すただならぬ性格のアナタは特質系かもしれません。<br>
            周囲に自然と人が集まってくるリーダー格のハンターです。</p>
        </div>
    <% end %>

    <% if @topic5.question == 20  %>
        <div class="col-13">
            <p>念の修行にはまだ早い！！</p>
        </div>
        <div class="col-10">
            <%= image_tag '/assets/tonpa.jpg', size: "250x250", class: 'hoge' %>
        </div>
        <div class="col-8">
            <p>あなたは念の習得をするには十分な実力がないようです。<br>
            まずは四大行を行った方がいいですよ！</p>
        </div>
    <% end %>
 
    <div class="col-9">
        <%= link_to"トップページに戻る",topics_top_path %>
    </div>
</div>

app/views/topics/new.html.erb
<div class="container-2">
    <div class="sindan-container">
        <div class="col-12">
            <p>Q1. ハンターたる者、争いは避けて通れません。あなたはどう行動しますか？</p>
        </div>
        <%= form_for(@topic, class: 'form-horizontal', role: 'form') do |f| %>
            <div class="col-6">
                <div class="col-7">
                    <%= f.radio_button :question, "1", id: "question_1" %>
                    <label for="question_1">全て争いで解決していく</label>
                </div>
                <div class="col-7">
                    <%= f.radio_button :question, "2", id: "question_2" %>
                    <label for="question_2">しなくても良い争いは避けて進む</label>
                </div>
            </div>
            <div class="sindanbotan">
                <%= f.submit "次へ", class: "button" %>
            </div>
        <% end %>
    </div>
</div>

app/views/topics/show.html.erb
<div class="container-2">
    <div class="sindan-container">
      <% if @topic.question == 1  %>
        <div class="col-12">
          <p>Q2.ハンターには体力も頭脳も必要。ではどちらがより重要でしょうか？</p>
        </div>
        <%= form_for(@topic2) do |f| %>
          <div class="col-6">
            <div class="col-7">
              <%= f.radio_button :question, "3", id: "question_3" %>
              <label for="question_3">体力</label>
            </div>
            <div class="col-7">
              <%= f.radio_button :question, "4", id: "question_4" %>
              <label for="question_4">頭脳</label>
            </div>
          </div>
          <div class="sindanbotan">
            <%= f.submit "次へ", class: "button" %>
          </div>
        <% end %>
      <% end %>

      <% if @topic.question == 2  %>
        <div class="col-12">
          <p>Q2.使いこなせばどんな物事にも応用が効く念能力。あなたは誰のために使いますか？</p>
        </div>
        <%= form_for(@topic2) do |f| %>
          <div class="col-6">
            <div class="col-7">
              <%= f.radio_button :question, "4", id: "question_4" %>
              <label for="question_4">自分のために使う</label>
            </div>
            <div class="col-7">
              <%= f.radio_button :question, "5", id: "question_5" %>
              <label for="question_5">周囲の人のために使う</label>
            </div>
          </div>
          <div class="sindanbotan">
            <%= f.submit "次へ", class: "button" %>
          </div>
        <% end %>
      <% end %>
  </div>
</div>

app/views/topics/top.html.erb
<div id="splash">
  <div id="splash_logo">
    <img src="/assets/logo.jpg" alt="" class="fadeUp">
  </div>
</div>
<div class="container">
  <div class="box">
    <h1>念能力診断</h1>
    <%= link_to "診断を始める", new_topic_path, class: "btn-sf-like" %>
  </div>
</div>


<canvas class="background"></canvas>